# Generated by Django 5.2.13 on 2026-04-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dummy_table',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('char_field', models.CharField(max_length=200)),
                ('text_field', models.TextField(blank=True)),
                ('int_field', models.IntegerField()),
                ('date_field', models.DateField()),
                ('dummy_table_id', models.BigAutoField(db_column='dummy_table_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_dummy_table',
                'abstract': False,
            },
        ),
    ]
