# Generated by Django 5.2.12 on 2026-05-03 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='metric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('value_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean'), ('string', 'String')], default='float', max_length=20)),
                ('aggregation_default', models.CharField(choices=[('avg', 'Average'), ('sum', 'Sum'), ('max', 'Max'), ('min', 'Minimum'), ('last', 'Last')], default='avg', max_length=20)),
                ('comparable_group', models.CharField(blank=True, db_index=True, max_length=100)),
                ('metric_id', models.BigAutoField(db_column='metric_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_metric',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='parse_run',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(db_index=True, max_length=50)),
                ('runner_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], db_index=True, default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('parse_run_id', models.BigAutoField(db_column='parse_run_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_parse_run',
                'indexes': [models.Index(fields=['source_system', '-started_at'], name='core_parse__source__f5fbb2_idx'), models.Index(fields=['status', '-started_at'], name='core_parse__status_b1bba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='source_file',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(db_index=True, max_length=50)),
                ('source_url', models.CharField(blank=True, max_length=1024)),
                ('source_file_name', models.CharField(max_length=512)),
                ('storage_path', models.CharField(max_length=1024)),
                ('file_type', models.CharField(default='CSV', max_length=20)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('detected_report_date', models.DateField(blank=True, db_index=True, null=True)),
                ('source_file_id', models.BigAutoField(db_column='source_file_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_source_file',
                'indexes': [models.Index(fields=['source_system', 'detected_report_date'], name='core_source_source__63cbec_idx'), models.Index(fields=['created_at'], name='core_source_created_c46278_idx')],
            },
        ),
        migrations.CreateModel(
            name='schema_mapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(db_index=True, max_length=50)),
                ('dataset_key', models.CharField(max_length=255)),
                ('raw_field_name', models.CharField(max_length=255)),
                ('target_kind', models.CharField(choices=[('metric', 'Metric'), ('dimension', 'Dimension'), ('timestamp', 'Timestamp')], max_length=20)),
                ('target_dimension_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transform_rule', models.JSONField(blank=True, default=dict)),
                ('schema_mapping_id', models.BigAutoField(db_column='schema_mapping_id', primary_key=True, serialize=False)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schema_mappings', to='core.metric')),
            ],
            options={
                'db_table': 'core_schema_mapping',
                'indexes': [models.Index(fields=['metric'], name='core_schema_metric__605c3f_idx')],
                'unique_together': {('source_system', 'dataset_key', 'raw_field_name')},
            },
        ),
        migrations.CreateModel(
            name='raw_record',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField()),
                ('row_payload_json', models.JSONField()),
                ('row_hash', models.CharField(max_length=64)),
                ('raw_record_id', models.BigAutoField(db_column='raw_record_id', primary_key=True, serialize=False)),
                ('parse_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.parse_run')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.source_file')),
            ],
            options={
                'db_table': 'core_raw_record',
                'indexes': [models.Index(fields=['source_file', 'row_number'], name='core_raw_re_source__0c1530_idx')],
                'unique_together': {('source_file', 'row_hash')},
            },
        ),
        migrations.CreateModel(
            name='parse_error',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('parse_error_id', models.BigAutoField(db_column='parse_error_id', primary_key=True, serialize=False)),
                ('parse_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.parse_run')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parse_errors', to='core.source_file')),
            ],
            options={
                'db_table': 'core_parse_error',
                'indexes': [models.Index(fields=['parse_run'], name='core_parse__parse_r_8ccbaa_idx'), models.Index(fields=['source_file'], name='core_parse__source__74311e_idx'), models.Index(fields=['error_type'], name='core_parse__error_t_daef63_idx')],
            },
        ),
        migrations.CreateModel(
            name='timeseries_point',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ts_utc', models.DateTimeField(db_index=True)),
                ('value_num', models.DecimalField(decimal_places=8, max_digits=20)),
                ('dimension_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dimension_key', models.CharField(blank=True, max_length=255, null=True)),
                ('quality_flag', models.CharField(blank=True, max_length=50, null=True)),
                ('source_row_hash', models.CharField(max_length=64)),
                ('timeseries_point_id', models.BigAutoField(db_column='timeseries_point_id', primary_key=True, serialize=False)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_points', to='core.metric')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_points', to='core.source_file')),
            ],
            options={
                'db_table': 'core_timeseries_point',
                'indexes': [models.Index(fields=['-ts_utc'], name='core_timese_ts_utc_9ab56d_idx'), models.Index(fields=['metric', '-ts_utc'], name='core_timese_metric__41b94d_idx'), models.Index(fields=['dimension_type', 'dimension_key', '-ts_utc'], name='core_timese_dimensi_efa531_idx')],
                'unique_together': {('source_file', 'metric', 'ts_utc', 'dimension_type', 'dimension_key', 'source_row_hash')},
            },
        ),
    ]
