# Generated by Django 5.2.12 on 2026-05-03 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_metric_parse_run_source_file_schema_mapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_definition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(db_index=True, max_length=64)),
                ('target_ref_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('interval_minutes', models.PositiveIntegerField(default=1440)),
                ('use_cache', models.BooleanField(default=True)),
                ('run_async', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('rolling_window_days', models.PositiveIntegerField(blank=True, null=True)),
                ('module_config_json', models.JSONField(blank=True, default=dict)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_state', models.CharField(choices=[('IDLE', 'Idle'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=16)),
                ('last_message', models.TextField(blank=True, default='')),
                ('schedule_definition_id', models.BigAutoField(db_column='schedule_definition_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_schedule_definition',
                'indexes': [models.Index(fields=['module_name', 'is_active', 'next_run_at'], name='core_schedu_module__c3ae49_idx'), models.Index(fields=['module_name', 'mode', 'is_active'], name='core_schedu_module__9daa17_idx')],
            },
        ),
        migrations.CreateModel(
            name='schedule_run',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(db_index=True, max_length=100)),
                ('triggered_by', models.CharField(default='scheduler', max_length=20)),
                ('state_value', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_targeted', models.IntegerField(default=0)),
                ('files_downloaded', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('schedule_run_id', models.BigAutoField(db_column='schedule_run_id', primary_key=True, serialize=False)),
                ('schedule_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.schedule_definition')),
            ],
            options={
                'db_table': 'core_schedule_run',
                'indexes': [models.Index(fields=['module_name', 'state_value', '-created_at'], name='core_schedu_module__3bcf5d_idx'), models.Index(fields=['schedule_definition', '-created_at'], name='core_schedu_schedul_55aa52_idx')],
            },
        ),
    ]
