# Generated by Django 5.2.13 on 2026-05-04 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule_definition_schedule_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='column_mapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(db_index=True, max_length=50)),
                ('dataset_key', models.CharField(max_length=255)),
                ('raw_column', models.CharField(max_length=255)),
                ('semantic_key', models.CharField(blank=True, max_length=255)),
                ('column_label', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('column_mapping_id', models.BigAutoField(db_column='column_mapping_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_column_mapping',
            },
        ),
        migrations.CreateModel(
            name='unit_type',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_name', models.CharField(max_length=100)),
                ('base_data_type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean'), ('string', 'String'), ('datetime', 'Datetime')], default='float', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit_type_id', models.BigAutoField(db_column='unit_type_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_unit_type',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='schema_mapping',
            name='metric',
        ),
        migrations.AlterUniqueTogether(
            name='schema_mapping',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='timeseries_point',
            name='core_timese_metric__41b94d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='timeseries_point',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeseries_point',
            name='column_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeseries_points', to='core.column_mapping'),
        ),
        migrations.AlterUniqueTogether(
            name='timeseries_point',
            unique_together={('source_file', 'column_mapping', 'ts_utc', 'dimension_type', 'dimension_key', 'source_row_hash')},
        ),
        migrations.AddIndex(
            model_name='timeseries_point',
            index=models.Index(fields=['column_mapping', '-ts_utc'], name='core_timese_column__511d59_idx'),
        ),
        migrations.AddField(
            model_name='column_mapping',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_mappings', to='core.unit_type'),
        ),
    ]
