# Generated by Django 5.2.13 on 2026-05-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_column_mapping_unit_type_and_more'),
        ('energy_hub', '0012_alter_nyiso_metric_alias_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schema_mapping',
        ),
        migrations.RemoveField(
            model_name='timeseries_point',
            name='metric',
        ),
        migrations.AddIndex(
            model_name='column_mapping',
            index=models.Index(fields=['unit_type'], name='core_column_unit_ty_dd1757_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='column_mapping',
            unique_together={('source_system', 'dataset_key', 'raw_column')},
        ),
        migrations.DeleteModel(
            name='metric',
        ),
    ]
