# Generated by Django 5.2.13 on 2026-05-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_schema_mapping_remove_timeseries_point_metric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chart_definition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('chart_type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('scatter', 'Scatter'), ('area', 'Area'), ('pie', 'Pie'), ('heatmap', 'Heatmap')], db_index=True, default='line', max_length=20)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('last_data_json', models.JSONField(blank=True, default=dict)),
                ('is_pinned', models.BooleanField(default=False)),
                ('chart_definition_id', models.BigAutoField(db_column='chart_definition_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_chart_definition',
                'indexes': [models.Index(fields=['chart_type'], name='core_chart__chart_t_5b9a8f_idx'), models.Index(fields=['-created_at'], name='core_chart__created_7aed2b_idx')],
            },
        ),
    ]
