# Generated by Django 5.2.13 on 2026-05-04 23:37

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chart_definition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeseries_point',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='timeseries_point',
            constraint=models.UniqueConstraint(models.F('source_file'), models.F('column_mapping'), models.F('ts_utc'), django.db.models.functions.comparison.Coalesce('dimension_type', models.Value('')), django.db.models.functions.comparison.Coalesce('dimension_key', models.Value('')), models.F('source_row_hash'), name='core_timeseries_point_dedup_uq'),
        ),
    ]
