# Generated by Django 5.2.13 on 2026-05-05 02:43

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_timeseries_point_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeseries_point',
            name='core_timeseries_point_dedup_uq',
        ),
        migrations.AddConstraint(
            model_name='timeseries_point',
            constraint=models.UniqueConstraint(models.F('column_mapping'), models.F('ts_utc'), django.db.models.functions.comparison.Coalesce('dimension_type', models.Value('')), django.db.models.functions.comparison.Coalesce('dimension_key', models.Value('')), models.F('source_row_hash'), name='core_timeseries_point_dedup_uq'),
        ),
    ]
