# Generated by Django 5.2.13 on 2026-05-05 16:50

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_timeseries_point_core_timeseries_point_dedup_uq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeseries_point',
            name='core_timeseries_point_dedup_uq',
        ),
        migrations.AddConstraint(
            model_name='timeseries_point',
            constraint=models.UniqueConstraint(models.F('column_mapping'), models.F('ts_utc'), django.db.models.functions.comparison.Coalesce('dimension_type', models.Value('')), django.db.models.functions.comparison.Coalesce('dimension_key', models.Value('')), name='core_timeseries_point_dedup_uq'),
        ),
    ]
