# Generated by Django 5.2.13 on 2026-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_timeseries_point_core_timeseries_point_dedup_uq_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeseries_point',
            name='core_timeseries_point_dedup_uq',
        ),
        migrations.RemoveIndex(
            model_name='timeseries_point',
            name='core_timese_dimensi_efa531_idx',
        ),
        migrations.RemoveField(
            model_name='timeseries_point',
            name='dimension_key',
        ),
        migrations.RemoveField(
            model_name='timeseries_point',
            name='dimension_type',
        ),
        migrations.RemoveField(
            model_name='timeseries_point',
            name='value_num',
        ),
        migrations.AddField(
            model_name='column_mapping',
            name='include_in_ingestion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeseries_point',
            name='value_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='timeseries_point',
            constraint=models.UniqueConstraint(models.F('column_mapping'), models.F('ts_utc'), name='core_timeseries_point_dedup_uq'),
        ),
    ]
