# Generated by Django 5.2.13 on 2026-05-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_timeseries_point_core_timeseries_point_dedup_uq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeseries_batch_audit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_code', models.CharField(db_index=True, max_length=64)),
                ('batch_index', models.PositiveIntegerField()),
                ('batch_start_row', models.IntegerField()),
                ('batch_end_row', models.IntegerField()),
                ('rows_read', models.IntegerField(default=0)),
                ('points_attempted', models.IntegerField(default=0)),
                ('points_written', models.IntegerField(default=0)),
                ('duplicates_estimated', models.IntegerField(default=0)),
                ('pre_validation_ok', models.BooleanField(default=True)),
                ('post_validation_ok', models.BooleanField(default=True)),
                ('invalid_timestamp_count', models.IntegerField(default=0)),
                ('off_interval_count', models.IntegerField(default=0)),
                ('gap_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('FAILED', 'Failed')], db_index=True, default='SUCCESS', max_length=16)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('timeseries_batch_audit_id', models.BigAutoField(db_column='timeseries_batch_audit_id', primary_key=True, serialize=False)),
                ('parse_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_batch_audits', to='core.parse_run')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries_batch_audits', to='core.source_file')),
            ],
            options={
                'db_table': 'core_timeseries_batch_audit',
                'indexes': [models.Index(fields=['report_code', 'batch_index'], name='core_timese_report__3973dc_idx'), models.Index(fields=['status', '-created_at'], name='core_timese_status_1f75b6_idx'), models.Index(fields=['source_file', '-created_at'], name='core_timese_source__e1662d_idx')],
            },
        ),
    ]
