# Generated by Django 5.2.14 on 2026-05-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_timeseries_batch_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseries_point',
            name='quality_flag',
        ),
        migrations.RemoveField(
            model_name='timeseries_point',
            name='source_row_hash',
        ),
    ]
