name: prvd_framework

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password6^
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    environment:
      - DATABASE_ENGINE=postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=app_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=Password6^
      - SERVER_ROOT=/app
      - MODULES_ROOT=/modules
    depends_on:
      - db   
    ports:
      - "8000:8000"
    volumes:
      - ../server:/app
      - ../modules:/modules

  ui:
    build:
      context: ..
      dockerfile: ./docker/client.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../client:/app
      - ../client/node_modules:/app/node_modules
      - ../modules:/modules
    environment:
      - NODE_ENV=development
      - VITE_INSPECT=true
      - VITE_API_PROXY_TARGET=http://api:8000
      - CHOKIDAR_USEPOLLING=true